name: "ECH"
on:
  # schedule:
  #   - cron: "0 * * * *"
  #   - cron: "20 * * * *"
  #   - cron: "40 * * * *"
permissions:
  contents: read

jobs:
  install:
    timeout-minutes: 60
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
 
      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
 
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
 
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
 
      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

  apm:
      needs: install
      name: Run tests (APM)
      timeout-minutes: 60
      runs-on: ubuntu-latest
      if: github.event.schedule == '0 * * * *'
      outputs:
        is_running: ${{ steps.set_output.outputs.is_running }}
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Indicate running status
        id: set_output
        run: echo "is_running=true" >> $GITHUB_OUTPUT
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
  
      - name: Cache Playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      
      - name: Run Playwright tests - APM
        run: npx playwright test apm.kibana.spec.ts --project kibana
        env:
          KIBANA_HOST: ${{ secrets.KIBANA_HOST_STATEFUL }}
          KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME_STATEFUL }}
          KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD_STATEFUL }}
          ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST_STATEFUL }}
          API_KEY: ${{ secrets.API_KEY_STATEFUL }}
          TIME_UNIT: ${{ vars.TIME_UNIT_DAYS }}
          TIME_VALUE: ${{ vars.TIME_VALUE_1 }}
          START_DATE: ${{ vars.START_DATE }}
          END_DATE: ${{ vars.END_DATE }}
          ABSOLUTE_TIME_RANGE_ECH: false

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: /home/runner/work/oblt-playwright/*.json
          retention-days: 1

  infra:
    needs: install
    name: Run tests (Infra)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.schedule == '20 * * * *'
    outputs:
        is_running: ${{ steps.set_output.outputs.is_running }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Indicate running status
      id: set_output
      run: echo "is_running=true" >> $GITHUB_OUTPUT
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
 
    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}
    
    - name: Run Playwright tests - Infra
      run: npx playwright test infra.kibana.spec.ts --project kibana
      env:
        KIBANA_HOST: ${{ secrets.KIBANA_HOST_STATEFUL }}
        KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME_STATEFUL }}
        KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD_STATEFUL }}
        ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST_STATEFUL }}
        API_KEY: ${{ secrets.API_KEY_STATEFUL }}
        TIME_UNIT: ${{ vars.TIME_UNIT_DAYS }}
        TIME_VALUE: ${{ vars.TIME_VALUE_1 }}
        START_DATE: ${{ vars.START_DATE }}
        END_DATE: ${{ vars.END_DATE }}
        ABSOLUTE_TIME_RANGE_ECH: false

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: /home/runner/work/oblt-playwright/*.json
        retention-days: 1

  logs:
    needs: install
    name: Run tests (Logs)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.schedule == '40 * * * *'
    outputs:
        is_running: ${{ steps.set_output.outputs.is_running }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Indicate running status
      id: set_output
      run: echo "is_running=true" >> $GITHUB_OUTPUT
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
 
    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}
    
    - name: Run Playwright tests - Logs
      run: npx playwright test logs.kibana.spec.ts --project kibana
      env:
        KIBANA_HOST: ${{ secrets.KIBANA_HOST_STATEFUL }}
        KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME_STATEFUL }}
        KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD_STATEFUL }}
        ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST_STATEFUL }}
        API_KEY: ${{ secrets.API_KEY_STATEFUL }}
        TIME_UNIT: ${{ vars.TIME_UNIT_DAYS }}
        TIME_VALUE: ${{ vars.TIME_VALUE_1 }}
        START_DATE: ${{ vars.START_DATE }}
        END_DATE: ${{ vars.END_DATE }}
        ABSOLUTE_TIME_RANGE_ECH: false

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: /home/runner/work/oblt-playwright/*.json
        retention-days: 1

  upload:
    needs:
      - apm
      - infra
      - logs
    if: always()
    name: Upload test reports to Elasticsearch
    runs-on: ubuntu-latest
    env:
        REPORTING_CLUSTER_API_KEY: ${{ secrets.REPORTING_CLUSTER_API_KEY }}
        REPORTING_CLUSTER_ES: ${{ secrets.REPORTING_CLUSTER_ES }}
        REPORTING_CLUSTER_INDEX: ${{ vars.REPORTING_CLUSTER_INDEX }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
  
    - name: Download raw test report from artifacts
      uses: actions/download-artifact@v5
      with:
        path: /home/runner/work/oblt-playwright/
        
    - name: Upload test report to Elasticsearch
      run: bash ./src/utils/upload_to_es.sh
