name: Serverless - SLOs performance tests
on: workflow_dispatch
permissions:
  contents: read

jobs:
  install:
    timeout-minutes: 60
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
 
      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
 
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
 
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
 
      - name: Install Chromium
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install-deps chromium

  test:
    needs: install
    timeout-minutes: 60
    name: Performance tests
    runs-on: ubuntu-latest
    env:
        API_KEY: ${{ secrets.API_KEY }}
        ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST }}
        KIBANA_HOST: ${{ secrets.KIBANA_HOST }}
        REPORT_FILE: ${{ secrets.REPORT_FILE }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
 
    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}
    
    - name: Run SLO transforms performance tests
      run: npx playwright test slos.api.spec.ts
      
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: perf-test-report
        path: /home/runner/work/oblt-playwright/test-results
        retention-days: 1

  upload:
    needs: test
    name: Upload test reports to Elasticsearch
    if: success()
    runs-on: ubuntu-latest
    env:
        API_KEY: ${{ secrets.API_KEY }}
        ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST }}
        ELASTIC_SLO_INDEX: ${{ secrets.ELASTIC_SLO_INDEX }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
  
    - name: Download raw test report from artifacts
      uses: actions/download-artifact@v4
      with:
        name: perf-test-report
        path: /home/runner/work/oblt-playwright
        
    - name: Upload test report to Elasticsearch
      run: bash ./src/utils/upload_to_es.sh
