name: "Serverless - Logs"
on:
  schedule:
    - cron: "0 * * * *"
    - cron: "*/30 * * * *"
permissions:
  contents: read

jobs:
  install:
    timeout-minutes: 60
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
 
      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
 
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
 
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
 
      - name: Install Chromium
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install-deps chromium

  test_7_days:
    needs: install
    name: Run tests (7 days)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/30 * * * *'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
 
    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}
    
    - name: Run Playwright tests
      run: npx playwright test logs.serverless.spec.ts --project serverless
      env:
        KIBANA_HOST: ${{ secrets.KIBANA_HOST }}
        KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME }}
        KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}
        TIME_UNIT: ${{ vars.TIME_UNIT }}
        TIME_VALUE: ${{ vars.TIME_VALUE_X }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: playwright-report/
        retention-days: 1

  test_14_days:
    needs: install
    name: Run tests (14 days)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 * * * *'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
 
    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}
    
    - name: Run Playwright tests
      run: npx playwright test logs.serverless.spec.ts --project serverless
      env:
        KIBANA_HOST: ${{ secrets.KIBANA_HOST }}
        KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME }}
        KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}
        TIME_UNIT: ${{ vars.TIME_UNIT }}
        TIME_VALUE: ${{ vars.TIME_VALUE_Y }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: playwright-report/
        retention-days: 1

  parse:
    needs:
      - test_7_days
      - test_14_days
    if: ${{ needs.test_7_days.result == 'completed' || needs.test_14_days.result == 'completed' }}
    name: Parse raw test report
    runs-on: ubuntu-latest
    env:
        REPORT_FILE: ${{ vars.REPORT_FILE }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
  
    - name: Download raw test report from artifacts
      uses: actions/download-artifact@v4
      with:
        path: /home/runner/work/oblt-playwright
        
    - name: Parse raw report
      run: node utils/split_json_report.js
      
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: perf-test-report
        path: /home/runner/work/oblt-playwright/test-results
        retention-days: 30

  upload:
    needs: parse
    if: ${{ needs.parse.result == 'completed' }}
    name: Upload test reports to Elasticsearch
    runs-on: ubuntu-latest
    env:
        REPORTING_CLUSTER_API_KEY: ${{ secrets.REPORTING_CLUSTER_API_KEY }}
        REPORTING_CLUSTER_ES: ${{ secrets.REPORTING_CLUSTER_ES }}
        REPORTING_CLUSTER_INDEX: ${{ vars.REPORTING_CLUSTER_INDEX }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
  
    - name: Download raw test report from artifacts
      uses: actions/download-artifact@v4
      with:
        name: perf-test-report
        path: /home/runner/work/oblt-playwright
        
    - name: Upload test report to Elasticsearch
      run: bash ./utils/upload_to_es.sh
